app = "alx-travel-app"
primary_region = "lax"

[build]

[env]
  DJANGO_SETTINGS_MODULE = "alx_travel_app.settings"

[processes]
  web = "gunicorn alx_travel_app.wsgi --log-file -"
  worker = "celery -A alx_travel_app worker --loglevel=INFO"
  beat = "celery -A alx_travel_app beat --loglevel=INFO"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
