app = "alx-celery-worker"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  DJANGO_SETTINGS_MODULE = "alx_travel_app.settings"
  DEBUG = "false"

[processes]
  worker = "celery -A alx_travel_app worker --loglevel=info"

[[services]]
  internal_port = 8000
  protocol = "tcp"
