services:
  - type: web
    name: alx-travel-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn alx_travel_app.wsgi --log-file -
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: travelapp.onrender.com

  - type: worker
    name: celery-worker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A alx_travel_app worker --loglevel=info
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: travelapp.onrender.com

  - type: rabbitmq
    name: rabbitmq
    plan: free
